/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-01 at 17:59:32 UTC 
 * Modify at your own risk.
 */

package singularity.com.jlpsi.entities.studentendpoint.model;

/**
 * Model definition for Student.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the studentendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Student extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean assigned;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String assignedBy;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long assignedTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String compDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String compSerial;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String picUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String regNo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String schoolId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAssigned() {
    return assigned;
  }

  /**
   * @param assigned assigned or {@code null} for none
   */
  public Student setAssigned(java.lang.Boolean assigned) {
    this.assigned = assigned;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAssignedBy() {
    return assignedBy;
  }

  /**
   * @param assignedBy assignedBy or {@code null} for none
   */
  public Student setAssignedBy(java.lang.String assignedBy) {
    this.assignedBy = assignedBy;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getAssignedTime() {
    return assignedTime;
  }

  /**
   * @param assignedTime assignedTime or {@code null} for none
   */
  public Student setAssignedTime(java.lang.Long assignedTime) {
    this.assignedTime = assignedTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCompDescription() {
    return compDescription;
  }

  /**
   * @param compDescription compDescription or {@code null} for none
   */
  public Student setCompDescription(java.lang.String compDescription) {
    this.compDescription = compDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCompSerial() {
    return compSerial;
  }

  /**
   * @param compSerial compSerial or {@code null} for none
   */
  public Student setCompSerial(java.lang.String compSerial) {
    this.compSerial = compSerial;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Student setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Student setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPicUrl() {
    return picUrl;
  }

  /**
   * @param picUrl picUrl or {@code null} for none
   */
  public Student setPicUrl(java.lang.String picUrl) {
    this.picUrl = picUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRegNo() {
    return regNo;
  }

  /**
   * @param regNo regNo or {@code null} for none
   */
  public Student setRegNo(java.lang.String regNo) {
    this.regNo = regNo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSchoolId() {
    return schoolId;
  }

  /**
   * @param schoolId schoolId or {@code null} for none
   */
  public Student setSchoolId(java.lang.String schoolId) {
    this.schoolId = schoolId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public Student setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  @Override
  public Student set(String fieldName, Object value) {
    return (Student) super.set(fieldName, value);
  }

  @Override
  public Student clone() {
    return (Student) super.clone();
  }

}
