/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-01 at 17:59:32 UTC 
 * Modify at your own risk.
 */

package singularity.com.jlpsi.entities.studentendpoint;

/**
 * Service definition for Studentendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link StudentendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Studentendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the studentendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://kiki-ke.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "studentendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Studentendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Studentendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getStudent".
   *
   * This request holds the parameters needed by the studentendpoint server.  After setting any
   * optional parameters, call the {@link GetStudent#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetStudent getStudent(java.lang.String id) throws java.io.IOException {
    GetStudent result = new GetStudent(id);
    initialize(result);
    return result;
  }

  public class GetStudent extends StudentendpointRequest<singularity.com.jlpsi.entities.studentendpoint.model.Student> {

    private static final String REST_PATH = "student/{id}";

    /**
     * Create a request for the method "getStudent".
     *
     * This request holds the parameters needed by the the studentendpoint server.  After setting any
     * optional parameters, call the {@link GetStudent#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetStudent#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetStudent(java.lang.String id) {
      super(Studentendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.studentendpoint.model.Student.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetStudent setAlt(java.lang.String alt) {
      return (GetStudent) super.setAlt(alt);
    }

    @Override
    public GetStudent setFields(java.lang.String fields) {
      return (GetStudent) super.setFields(fields);
    }

    @Override
    public GetStudent setKey(java.lang.String key) {
      return (GetStudent) super.setKey(key);
    }

    @Override
    public GetStudent setOauthToken(java.lang.String oauthToken) {
      return (GetStudent) super.setOauthToken(oauthToken);
    }

    @Override
    public GetStudent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetStudent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetStudent setQuotaUser(java.lang.String quotaUser) {
      return (GetStudent) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetStudent setUserIp(java.lang.String userIp) {
      return (GetStudent) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetStudent setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetStudent set(String parameterName, Object value) {
      return (GetStudent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertStudent".
   *
   * This request holds the parameters needed by the studentendpoint server.  After setting any
   * optional parameters, call the {@link InsertStudent#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.studentendpoint.model.Student}
   * @return the request
   */
  public InsertStudent insertStudent(singularity.com.jlpsi.entities.studentendpoint.model.Student content) throws java.io.IOException {
    InsertStudent result = new InsertStudent(content);
    initialize(result);
    return result;
  }

  public class InsertStudent extends StudentendpointRequest<singularity.com.jlpsi.entities.studentendpoint.model.Student> {

    private static final String REST_PATH = "student";

    /**
     * Create a request for the method "insertStudent".
     *
     * This request holds the parameters needed by the the studentendpoint server.  After setting any
     * optional parameters, call the {@link InsertStudent#execute()} method to invoke the remote
     * operation. <p> {@link InsertStudent#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.studentendpoint.model.Student}
     * @since 1.13
     */
    protected InsertStudent(singularity.com.jlpsi.entities.studentendpoint.model.Student content) {
      super(Studentendpoint.this, "POST", REST_PATH, content, singularity.com.jlpsi.entities.studentendpoint.model.Student.class);
    }

    @Override
    public InsertStudent setAlt(java.lang.String alt) {
      return (InsertStudent) super.setAlt(alt);
    }

    @Override
    public InsertStudent setFields(java.lang.String fields) {
      return (InsertStudent) super.setFields(fields);
    }

    @Override
    public InsertStudent setKey(java.lang.String key) {
      return (InsertStudent) super.setKey(key);
    }

    @Override
    public InsertStudent setOauthToken(java.lang.String oauthToken) {
      return (InsertStudent) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertStudent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertStudent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertStudent setQuotaUser(java.lang.String quotaUser) {
      return (InsertStudent) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertStudent setUserIp(java.lang.String userIp) {
      return (InsertStudent) super.setUserIp(userIp);
    }

    @Override
    public InsertStudent set(String parameterName, Object value) {
      return (InsertStudent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listStudent".
   *
   * This request holds the parameters needed by the studentendpoint server.  After setting any
   * optional parameters, call the {@link ListStudent#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListStudent listStudent() throws java.io.IOException {
    ListStudent result = new ListStudent();
    initialize(result);
    return result;
  }

  public class ListStudent extends StudentendpointRequest<singularity.com.jlpsi.entities.studentendpoint.model.CollectionResponseStudent> {

    private static final String REST_PATH = "student";

    /**
     * Create a request for the method "listStudent".
     *
     * This request holds the parameters needed by the the studentendpoint server.  After setting any
     * optional parameters, call the {@link ListStudent#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListStudent#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListStudent() {
      super(Studentendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.studentendpoint.model.CollectionResponseStudent.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListStudent setAlt(java.lang.String alt) {
      return (ListStudent) super.setAlt(alt);
    }

    @Override
    public ListStudent setFields(java.lang.String fields) {
      return (ListStudent) super.setFields(fields);
    }

    @Override
    public ListStudent setKey(java.lang.String key) {
      return (ListStudent) super.setKey(key);
    }

    @Override
    public ListStudent setOauthToken(java.lang.String oauthToken) {
      return (ListStudent) super.setOauthToken(oauthToken);
    }

    @Override
    public ListStudent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListStudent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListStudent setQuotaUser(java.lang.String quotaUser) {
      return (ListStudent) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListStudent setUserIp(java.lang.String userIp) {
      return (ListStudent) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListStudent setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String schoolId;

    /**

     */
    public java.lang.String getSchoolId() {
      return schoolId;
    }

    public ListStudent setSchoolId(java.lang.String schoolId) {
      this.schoolId = schoolId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListStudent setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListStudent set(String parameterName, Object value) {
      return (ListStudent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeStudent".
   *
   * This request holds the parameters needed by the studentendpoint server.  After setting any
   * optional parameters, call the {@link RemoveStudent#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveStudent removeStudent(java.lang.String id) throws java.io.IOException {
    RemoveStudent result = new RemoveStudent(id);
    initialize(result);
    return result;
  }

  public class RemoveStudent extends StudentendpointRequest<Void> {

    private static final String REST_PATH = "student/{id}";

    /**
     * Create a request for the method "removeStudent".
     *
     * This request holds the parameters needed by the the studentendpoint server.  After setting any
     * optional parameters, call the {@link RemoveStudent#execute()} method to invoke the remote
     * operation. <p> {@link RemoveStudent#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveStudent(java.lang.String id) {
      super(Studentendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveStudent setAlt(java.lang.String alt) {
      return (RemoveStudent) super.setAlt(alt);
    }

    @Override
    public RemoveStudent setFields(java.lang.String fields) {
      return (RemoveStudent) super.setFields(fields);
    }

    @Override
    public RemoveStudent setKey(java.lang.String key) {
      return (RemoveStudent) super.setKey(key);
    }

    @Override
    public RemoveStudent setOauthToken(java.lang.String oauthToken) {
      return (RemoveStudent) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveStudent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveStudent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveStudent setQuotaUser(java.lang.String quotaUser) {
      return (RemoveStudent) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveStudent setUserIp(java.lang.String userIp) {
      return (RemoveStudent) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveStudent setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveStudent set(String parameterName, Object value) {
      return (RemoveStudent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateStudent".
   *
   * This request holds the parameters needed by the studentendpoint server.  After setting any
   * optional parameters, call the {@link UpdateStudent#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.studentendpoint.model.Student}
   * @return the request
   */
  public UpdateStudent updateStudent(singularity.com.jlpsi.entities.studentendpoint.model.Student content) throws java.io.IOException {
    UpdateStudent result = new UpdateStudent(content);
    initialize(result);
    return result;
  }

  public class UpdateStudent extends StudentendpointRequest<singularity.com.jlpsi.entities.studentendpoint.model.Student> {

    private static final String REST_PATH = "student";

    /**
     * Create a request for the method "updateStudent".
     *
     * This request holds the parameters needed by the the studentendpoint server.  After setting any
     * optional parameters, call the {@link UpdateStudent#execute()} method to invoke the remote
     * operation. <p> {@link UpdateStudent#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.studentendpoint.model.Student}
     * @since 1.13
     */
    protected UpdateStudent(singularity.com.jlpsi.entities.studentendpoint.model.Student content) {
      super(Studentendpoint.this, "PUT", REST_PATH, content, singularity.com.jlpsi.entities.studentendpoint.model.Student.class);
    }

    @Override
    public UpdateStudent setAlt(java.lang.String alt) {
      return (UpdateStudent) super.setAlt(alt);
    }

    @Override
    public UpdateStudent setFields(java.lang.String fields) {
      return (UpdateStudent) super.setFields(fields);
    }

    @Override
    public UpdateStudent setKey(java.lang.String key) {
      return (UpdateStudent) super.setKey(key);
    }

    @Override
    public UpdateStudent setOauthToken(java.lang.String oauthToken) {
      return (UpdateStudent) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateStudent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateStudent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateStudent setQuotaUser(java.lang.String quotaUser) {
      return (UpdateStudent) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateStudent setUserIp(java.lang.String userIp) {
      return (UpdateStudent) super.setUserIp(userIp);
    }

    @Override
    public UpdateStudent set(String parameterName, Object value) {
      return (UpdateStudent) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Studentendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Studentendpoint}. */
    @Override
    public Studentendpoint build() {
      return new Studentendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link StudentendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setStudentendpointRequestInitializer(
        StudentendpointRequestInitializer studentendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(studentendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
