/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-01 at 17:52:36 UTC 
 * Modify at your own risk.
 */

package singularity.com.jlpsi.entities.statsendpoint;

/**
 * Service definition for Statsendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link StatsendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Statsendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the statsendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://kiki-ke.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "statsendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Statsendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Statsendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getStats".
   *
   * This request holds the parameters needed by the statsendpoint server.  After setting any optional
   * parameters, call the {@link GetStats#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetStats getStats(java.lang.String id) throws java.io.IOException {
    GetStats result = new GetStats(id);
    initialize(result);
    return result;
  }

  public class GetStats extends StatsendpointRequest<singularity.com.jlpsi.entities.statsendpoint.model.Stats> {

    private static final String REST_PATH = "stats/{id}";

    /**
     * Create a request for the method "getStats".
     *
     * This request holds the parameters needed by the the statsendpoint server.  After setting any
     * optional parameters, call the {@link GetStats#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetStats#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetStats(java.lang.String id) {
      super(Statsendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.statsendpoint.model.Stats.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetStats setAlt(java.lang.String alt) {
      return (GetStats) super.setAlt(alt);
    }

    @Override
    public GetStats setFields(java.lang.String fields) {
      return (GetStats) super.setFields(fields);
    }

    @Override
    public GetStats setKey(java.lang.String key) {
      return (GetStats) super.setKey(key);
    }

    @Override
    public GetStats setOauthToken(java.lang.String oauthToken) {
      return (GetStats) super.setOauthToken(oauthToken);
    }

    @Override
    public GetStats setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetStats) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetStats setQuotaUser(java.lang.String quotaUser) {
      return (GetStats) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetStats setUserIp(java.lang.String userIp) {
      return (GetStats) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetStats setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetStats set(String parameterName, Object value) {
      return (GetStats) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertStats".
   *
   * This request holds the parameters needed by the statsendpoint server.  After setting any optional
   * parameters, call the {@link InsertStats#execute()} method to invoke the remote operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.statsendpoint.model.Stats}
   * @return the request
   */
  public InsertStats insertStats(singularity.com.jlpsi.entities.statsendpoint.model.Stats content) throws java.io.IOException {
    InsertStats result = new InsertStats(content);
    initialize(result);
    return result;
  }

  public class InsertStats extends StatsendpointRequest<singularity.com.jlpsi.entities.statsendpoint.model.Stats> {

    private static final String REST_PATH = "stats";

    /**
     * Create a request for the method "insertStats".
     *
     * This request holds the parameters needed by the the statsendpoint server.  After setting any
     * optional parameters, call the {@link InsertStats#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertStats#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.statsendpoint.model.Stats}
     * @since 1.13
     */
    protected InsertStats(singularity.com.jlpsi.entities.statsendpoint.model.Stats content) {
      super(Statsendpoint.this, "POST", REST_PATH, content, singularity.com.jlpsi.entities.statsendpoint.model.Stats.class);
    }

    @Override
    public InsertStats setAlt(java.lang.String alt) {
      return (InsertStats) super.setAlt(alt);
    }

    @Override
    public InsertStats setFields(java.lang.String fields) {
      return (InsertStats) super.setFields(fields);
    }

    @Override
    public InsertStats setKey(java.lang.String key) {
      return (InsertStats) super.setKey(key);
    }

    @Override
    public InsertStats setOauthToken(java.lang.String oauthToken) {
      return (InsertStats) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertStats setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertStats) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertStats setQuotaUser(java.lang.String quotaUser) {
      return (InsertStats) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertStats setUserIp(java.lang.String userIp) {
      return (InsertStats) super.setUserIp(userIp);
    }

    @Override
    public InsertStats set(String parameterName, Object value) {
      return (InsertStats) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listStats".
   *
   * This request holds the parameters needed by the statsendpoint server.  After setting any optional
   * parameters, call the {@link ListStats#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListStats listStats() throws java.io.IOException {
    ListStats result = new ListStats();
    initialize(result);
    return result;
  }

  public class ListStats extends StatsendpointRequest<singularity.com.jlpsi.entities.statsendpoint.model.CollectionResponseStats> {

    private static final String REST_PATH = "stats";

    /**
     * Create a request for the method "listStats".
     *
     * This request holds the parameters needed by the the statsendpoint server.  After setting any
     * optional parameters, call the {@link ListStats#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListStats#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListStats() {
      super(Statsendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.statsendpoint.model.CollectionResponseStats.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListStats setAlt(java.lang.String alt) {
      return (ListStats) super.setAlt(alt);
    }

    @Override
    public ListStats setFields(java.lang.String fields) {
      return (ListStats) super.setFields(fields);
    }

    @Override
    public ListStats setKey(java.lang.String key) {
      return (ListStats) super.setKey(key);
    }

    @Override
    public ListStats setOauthToken(java.lang.String oauthToken) {
      return (ListStats) super.setOauthToken(oauthToken);
    }

    @Override
    public ListStats setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListStats) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListStats setQuotaUser(java.lang.String quotaUser) {
      return (ListStats) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListStats setUserIp(java.lang.String userIp) {
      return (ListStats) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListStats setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListStats setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListStats set(String parameterName, Object value) {
      return (ListStats) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeStats".
   *
   * This request holds the parameters needed by the statsendpoint server.  After setting any optional
   * parameters, call the {@link RemoveStats#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveStats removeStats(java.lang.String id) throws java.io.IOException {
    RemoveStats result = new RemoveStats(id);
    initialize(result);
    return result;
  }

  public class RemoveStats extends StatsendpointRequest<Void> {

    private static final String REST_PATH = "stats/{id}";

    /**
     * Create a request for the method "removeStats".
     *
     * This request holds the parameters needed by the the statsendpoint server.  After setting any
     * optional parameters, call the {@link RemoveStats#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveStats#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveStats(java.lang.String id) {
      super(Statsendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveStats setAlt(java.lang.String alt) {
      return (RemoveStats) super.setAlt(alt);
    }

    @Override
    public RemoveStats setFields(java.lang.String fields) {
      return (RemoveStats) super.setFields(fields);
    }

    @Override
    public RemoveStats setKey(java.lang.String key) {
      return (RemoveStats) super.setKey(key);
    }

    @Override
    public RemoveStats setOauthToken(java.lang.String oauthToken) {
      return (RemoveStats) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveStats setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveStats) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveStats setQuotaUser(java.lang.String quotaUser) {
      return (RemoveStats) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveStats setUserIp(java.lang.String userIp) {
      return (RemoveStats) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveStats setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveStats set(String parameterName, Object value) {
      return (RemoveStats) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateStats".
   *
   * This request holds the parameters needed by the statsendpoint server.  After setting any optional
   * parameters, call the {@link UpdateStats#execute()} method to invoke the remote operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.statsendpoint.model.Stats}
   * @return the request
   */
  public UpdateStats updateStats(singularity.com.jlpsi.entities.statsendpoint.model.Stats content) throws java.io.IOException {
    UpdateStats result = new UpdateStats(content);
    initialize(result);
    return result;
  }

  public class UpdateStats extends StatsendpointRequest<singularity.com.jlpsi.entities.statsendpoint.model.Stats> {

    private static final String REST_PATH = "stats";

    /**
     * Create a request for the method "updateStats".
     *
     * This request holds the parameters needed by the the statsendpoint server.  After setting any
     * optional parameters, call the {@link UpdateStats#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateStats#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.statsendpoint.model.Stats}
     * @since 1.13
     */
    protected UpdateStats(singularity.com.jlpsi.entities.statsendpoint.model.Stats content) {
      super(Statsendpoint.this, "PUT", REST_PATH, content, singularity.com.jlpsi.entities.statsendpoint.model.Stats.class);
    }

    @Override
    public UpdateStats setAlt(java.lang.String alt) {
      return (UpdateStats) super.setAlt(alt);
    }

    @Override
    public UpdateStats setFields(java.lang.String fields) {
      return (UpdateStats) super.setFields(fields);
    }

    @Override
    public UpdateStats setKey(java.lang.String key) {
      return (UpdateStats) super.setKey(key);
    }

    @Override
    public UpdateStats setOauthToken(java.lang.String oauthToken) {
      return (UpdateStats) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateStats setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateStats) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateStats setQuotaUser(java.lang.String quotaUser) {
      return (UpdateStats) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateStats setUserIp(java.lang.String userIp) {
      return (UpdateStats) super.setUserIp(userIp);
    }

    @Override
    public UpdateStats set(String parameterName, Object value) {
      return (UpdateStats) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Statsendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Statsendpoint}. */
    @Override
    public Statsendpoint build() {
      return new Statsendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link StatsendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setStatsendpointRequestInitializer(
        StatsendpointRequestInitializer statsendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(statsendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
