/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-01 at 17:55:22 UTC 
 * Modify at your own risk.
 */

package singularity.com.jlpsi.entities.softwareendpoint;

/**
 * Service definition for Softwareendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link SoftwareendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Softwareendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the softwareendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://kiki-ke.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "softwareendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Softwareendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Softwareendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getSoftware".
   *
   * This request holds the parameters needed by the softwareendpoint server.  After setting any
   * optional parameters, call the {@link GetSoftware#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetSoftware getSoftware(java.lang.String id) throws java.io.IOException {
    GetSoftware result = new GetSoftware(id);
    initialize(result);
    return result;
  }

  public class GetSoftware extends SoftwareendpointRequest<singularity.com.jlpsi.entities.softwareendpoint.model.Software> {

    private static final String REST_PATH = "software/{id}";

    /**
     * Create a request for the method "getSoftware".
     *
     * This request holds the parameters needed by the the softwareendpoint server.  After setting any
     * optional parameters, call the {@link GetSoftware#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetSoftware#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetSoftware(java.lang.String id) {
      super(Softwareendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.softwareendpoint.model.Software.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetSoftware setAlt(java.lang.String alt) {
      return (GetSoftware) super.setAlt(alt);
    }

    @Override
    public GetSoftware setFields(java.lang.String fields) {
      return (GetSoftware) super.setFields(fields);
    }

    @Override
    public GetSoftware setKey(java.lang.String key) {
      return (GetSoftware) super.setKey(key);
    }

    @Override
    public GetSoftware setOauthToken(java.lang.String oauthToken) {
      return (GetSoftware) super.setOauthToken(oauthToken);
    }

    @Override
    public GetSoftware setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetSoftware) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetSoftware setQuotaUser(java.lang.String quotaUser) {
      return (GetSoftware) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetSoftware setUserIp(java.lang.String userIp) {
      return (GetSoftware) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetSoftware setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetSoftware set(String parameterName, Object value) {
      return (GetSoftware) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertSoftware".
   *
   * This request holds the parameters needed by the softwareendpoint server.  After setting any
   * optional parameters, call the {@link InsertSoftware#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.softwareendpoint.model.Software}
   * @return the request
   */
  public InsertSoftware insertSoftware(singularity.com.jlpsi.entities.softwareendpoint.model.Software content) throws java.io.IOException {
    InsertSoftware result = new InsertSoftware(content);
    initialize(result);
    return result;
  }

  public class InsertSoftware extends SoftwareendpointRequest<singularity.com.jlpsi.entities.softwareendpoint.model.Software> {

    private static final String REST_PATH = "software";

    /**
     * Create a request for the method "insertSoftware".
     *
     * This request holds the parameters needed by the the softwareendpoint server.  After setting any
     * optional parameters, call the {@link InsertSoftware#execute()} method to invoke the remote
     * operation. <p> {@link InsertSoftware#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.softwareendpoint.model.Software}
     * @since 1.13
     */
    protected InsertSoftware(singularity.com.jlpsi.entities.softwareendpoint.model.Software content) {
      super(Softwareendpoint.this, "POST", REST_PATH, content, singularity.com.jlpsi.entities.softwareendpoint.model.Software.class);
    }

    @Override
    public InsertSoftware setAlt(java.lang.String alt) {
      return (InsertSoftware) super.setAlt(alt);
    }

    @Override
    public InsertSoftware setFields(java.lang.String fields) {
      return (InsertSoftware) super.setFields(fields);
    }

    @Override
    public InsertSoftware setKey(java.lang.String key) {
      return (InsertSoftware) super.setKey(key);
    }

    @Override
    public InsertSoftware setOauthToken(java.lang.String oauthToken) {
      return (InsertSoftware) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertSoftware setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertSoftware) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertSoftware setQuotaUser(java.lang.String quotaUser) {
      return (InsertSoftware) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertSoftware setUserIp(java.lang.String userIp) {
      return (InsertSoftware) super.setUserIp(userIp);
    }

    @Override
    public InsertSoftware set(String parameterName, Object value) {
      return (InsertSoftware) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listSoftware".
   *
   * This request holds the parameters needed by the softwareendpoint server.  After setting any
   * optional parameters, call the {@link ListSoftware#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListSoftware listSoftware() throws java.io.IOException {
    ListSoftware result = new ListSoftware();
    initialize(result);
    return result;
  }

  public class ListSoftware extends SoftwareendpointRequest<singularity.com.jlpsi.entities.softwareendpoint.model.CollectionResponseSoftware> {

    private static final String REST_PATH = "software";

    /**
     * Create a request for the method "listSoftware".
     *
     * This request holds the parameters needed by the the softwareendpoint server.  After setting any
     * optional parameters, call the {@link ListSoftware#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListSoftware#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListSoftware() {
      super(Softwareendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.softwareendpoint.model.CollectionResponseSoftware.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListSoftware setAlt(java.lang.String alt) {
      return (ListSoftware) super.setAlt(alt);
    }

    @Override
    public ListSoftware setFields(java.lang.String fields) {
      return (ListSoftware) super.setFields(fields);
    }

    @Override
    public ListSoftware setKey(java.lang.String key) {
      return (ListSoftware) super.setKey(key);
    }

    @Override
    public ListSoftware setOauthToken(java.lang.String oauthToken) {
      return (ListSoftware) super.setOauthToken(oauthToken);
    }

    @Override
    public ListSoftware setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListSoftware) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListSoftware setQuotaUser(java.lang.String quotaUser) {
      return (ListSoftware) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListSoftware setUserIp(java.lang.String userIp) {
      return (ListSoftware) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListSoftware setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListSoftware setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListSoftware set(String parameterName, Object value) {
      return (ListSoftware) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeSoftware".
   *
   * This request holds the parameters needed by the softwareendpoint server.  After setting any
   * optional parameters, call the {@link RemoveSoftware#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveSoftware removeSoftware(java.lang.String id) throws java.io.IOException {
    RemoveSoftware result = new RemoveSoftware(id);
    initialize(result);
    return result;
  }

  public class RemoveSoftware extends SoftwareendpointRequest<Void> {

    private static final String REST_PATH = "software/{id}";

    /**
     * Create a request for the method "removeSoftware".
     *
     * This request holds the parameters needed by the the softwareendpoint server.  After setting any
     * optional parameters, call the {@link RemoveSoftware#execute()} method to invoke the remote
     * operation. <p> {@link RemoveSoftware#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveSoftware(java.lang.String id) {
      super(Softwareendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveSoftware setAlt(java.lang.String alt) {
      return (RemoveSoftware) super.setAlt(alt);
    }

    @Override
    public RemoveSoftware setFields(java.lang.String fields) {
      return (RemoveSoftware) super.setFields(fields);
    }

    @Override
    public RemoveSoftware setKey(java.lang.String key) {
      return (RemoveSoftware) super.setKey(key);
    }

    @Override
    public RemoveSoftware setOauthToken(java.lang.String oauthToken) {
      return (RemoveSoftware) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveSoftware setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveSoftware) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveSoftware setQuotaUser(java.lang.String quotaUser) {
      return (RemoveSoftware) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveSoftware setUserIp(java.lang.String userIp) {
      return (RemoveSoftware) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveSoftware setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveSoftware set(String parameterName, Object value) {
      return (RemoveSoftware) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateSoftware".
   *
   * This request holds the parameters needed by the softwareendpoint server.  After setting any
   * optional parameters, call the {@link UpdateSoftware#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.softwareendpoint.model.Software}
   * @return the request
   */
  public UpdateSoftware updateSoftware(singularity.com.jlpsi.entities.softwareendpoint.model.Software content) throws java.io.IOException {
    UpdateSoftware result = new UpdateSoftware(content);
    initialize(result);
    return result;
  }

  public class UpdateSoftware extends SoftwareendpointRequest<singularity.com.jlpsi.entities.softwareendpoint.model.Software> {

    private static final String REST_PATH = "software";

    /**
     * Create a request for the method "updateSoftware".
     *
     * This request holds the parameters needed by the the softwareendpoint server.  After setting any
     * optional parameters, call the {@link UpdateSoftware#execute()} method to invoke the remote
     * operation. <p> {@link UpdateSoftware#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.softwareendpoint.model.Software}
     * @since 1.13
     */
    protected UpdateSoftware(singularity.com.jlpsi.entities.softwareendpoint.model.Software content) {
      super(Softwareendpoint.this, "PUT", REST_PATH, content, singularity.com.jlpsi.entities.softwareendpoint.model.Software.class);
    }

    @Override
    public UpdateSoftware setAlt(java.lang.String alt) {
      return (UpdateSoftware) super.setAlt(alt);
    }

    @Override
    public UpdateSoftware setFields(java.lang.String fields) {
      return (UpdateSoftware) super.setFields(fields);
    }

    @Override
    public UpdateSoftware setKey(java.lang.String key) {
      return (UpdateSoftware) super.setKey(key);
    }

    @Override
    public UpdateSoftware setOauthToken(java.lang.String oauthToken) {
      return (UpdateSoftware) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateSoftware setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateSoftware) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateSoftware setQuotaUser(java.lang.String quotaUser) {
      return (UpdateSoftware) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateSoftware setUserIp(java.lang.String userIp) {
      return (UpdateSoftware) super.setUserIp(userIp);
    }

    @Override
    public UpdateSoftware set(String parameterName, Object value) {
      return (UpdateSoftware) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Softwareendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Softwareendpoint}. */
    @Override
    public Softwareendpoint build() {
      return new Softwareendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link SoftwareendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setSoftwareendpointRequestInitializer(
        SoftwareendpointRequestInitializer softwareendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(softwareendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
