/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-01 at 17:50:56 UTC 
 * Modify at your own risk.
 */

package singularity.com.jlpsi.entities.backboneendpoint.model;

/**
 * Model definition for Computer.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the backboneendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Computer extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean assigned;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String assignedTo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String condition;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String model;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String notes;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String packageCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String schoolId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String serial;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long time;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAssigned() {
    return assigned;
  }

  /**
   * @param assigned assigned or {@code null} for none
   */
  public Computer setAssigned(java.lang.Boolean assigned) {
    this.assigned = assigned;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAssignedTo() {
    return assignedTo;
  }

  /**
   * @param assignedTo assignedTo or {@code null} for none
   */
  public Computer setAssignedTo(java.lang.String assignedTo) {
    this.assignedTo = assignedTo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCondition() {
    return condition;
  }

  /**
   * @param condition condition or {@code null} for none
   */
  public Computer setCondition(java.lang.String condition) {
    this.condition = condition;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Computer setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getModel() {
    return model;
  }

  /**
   * @param model model or {@code null} for none
   */
  public Computer setModel(java.lang.String model) {
    this.model = model;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNotes() {
    return notes;
  }

  /**
   * @param notes notes or {@code null} for none
   */
  public Computer setNotes(java.lang.String notes) {
    this.notes = notes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPackageCode() {
    return packageCode;
  }

  /**
   * @param packageCode packageCode or {@code null} for none
   */
  public Computer setPackageCode(java.lang.String packageCode) {
    this.packageCode = packageCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSchoolId() {
    return schoolId;
  }

  /**
   * @param schoolId schoolId or {@code null} for none
   */
  public Computer setSchoolId(java.lang.String schoolId) {
    this.schoolId = schoolId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSerial() {
    return serial;
  }

  /**
   * @param serial serial or {@code null} for none
   */
  public Computer setSerial(java.lang.String serial) {
    this.serial = serial;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTime() {
    return time;
  }

  /**
   * @param time time or {@code null} for none
   */
  public Computer setTime(java.lang.Long time) {
    this.time = time;
    return this;
  }

  @Override
  public Computer set(String fieldName, Object value) {
    return (Computer) super.set(fieldName, value);
  }

  @Override
  public Computer clone() {
    return (Computer) super.clone();
  }

}
