/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-01 at 17:49:29 UTC 
 * Modify at your own risk.
 */

package singularity.com.jlpsi.entities.computerendpoint;

/**
 * Service definition for Computerendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ComputerendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Computerendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the computerendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://kiki-ke.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "computerendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Computerendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Computerendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getComputer".
   *
   * This request holds the parameters needed by the computerendpoint server.  After setting any
   * optional parameters, call the {@link GetComputer#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetComputer getComputer(java.lang.String id) throws java.io.IOException {
    GetComputer result = new GetComputer(id);
    initialize(result);
    return result;
  }

  public class GetComputer extends ComputerendpointRequest<singularity.com.jlpsi.entities.computerendpoint.model.Computer> {

    private static final String REST_PATH = "computer/{id}";

    /**
     * Create a request for the method "getComputer".
     *
     * This request holds the parameters needed by the the computerendpoint server.  After setting any
     * optional parameters, call the {@link GetComputer#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetComputer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetComputer(java.lang.String id) {
      super(Computerendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.computerendpoint.model.Computer.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetComputer setAlt(java.lang.String alt) {
      return (GetComputer) super.setAlt(alt);
    }

    @Override
    public GetComputer setFields(java.lang.String fields) {
      return (GetComputer) super.setFields(fields);
    }

    @Override
    public GetComputer setKey(java.lang.String key) {
      return (GetComputer) super.setKey(key);
    }

    @Override
    public GetComputer setOauthToken(java.lang.String oauthToken) {
      return (GetComputer) super.setOauthToken(oauthToken);
    }

    @Override
    public GetComputer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetComputer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetComputer setQuotaUser(java.lang.String quotaUser) {
      return (GetComputer) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetComputer setUserIp(java.lang.String userIp) {
      return (GetComputer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetComputer setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetComputer set(String parameterName, Object value) {
      return (GetComputer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertComputer".
   *
   * This request holds the parameters needed by the computerendpoint server.  After setting any
   * optional parameters, call the {@link InsertComputer#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.computerendpoint.model.Computer}
   * @return the request
   */
  public InsertComputer insertComputer(singularity.com.jlpsi.entities.computerendpoint.model.Computer content) throws java.io.IOException {
    InsertComputer result = new InsertComputer(content);
    initialize(result);
    return result;
  }

  public class InsertComputer extends ComputerendpointRequest<singularity.com.jlpsi.entities.computerendpoint.model.Computer> {

    private static final String REST_PATH = "computer";

    /**
     * Create a request for the method "insertComputer".
     *
     * This request holds the parameters needed by the the computerendpoint server.  After setting any
     * optional parameters, call the {@link InsertComputer#execute()} method to invoke the remote
     * operation. <p> {@link InsertComputer#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.computerendpoint.model.Computer}
     * @since 1.13
     */
    protected InsertComputer(singularity.com.jlpsi.entities.computerendpoint.model.Computer content) {
      super(Computerendpoint.this, "POST", REST_PATH, content, singularity.com.jlpsi.entities.computerendpoint.model.Computer.class);
    }

    @Override
    public InsertComputer setAlt(java.lang.String alt) {
      return (InsertComputer) super.setAlt(alt);
    }

    @Override
    public InsertComputer setFields(java.lang.String fields) {
      return (InsertComputer) super.setFields(fields);
    }

    @Override
    public InsertComputer setKey(java.lang.String key) {
      return (InsertComputer) super.setKey(key);
    }

    @Override
    public InsertComputer setOauthToken(java.lang.String oauthToken) {
      return (InsertComputer) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertComputer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertComputer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertComputer setQuotaUser(java.lang.String quotaUser) {
      return (InsertComputer) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertComputer setUserIp(java.lang.String userIp) {
      return (InsertComputer) super.setUserIp(userIp);
    }

    @Override
    public InsertComputer set(String parameterName, Object value) {
      return (InsertComputer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listComputer".
   *
   * This request holds the parameters needed by the computerendpoint server.  After setting any
   * optional parameters, call the {@link ListComputer#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListComputer listComputer() throws java.io.IOException {
    ListComputer result = new ListComputer();
    initialize(result);
    return result;
  }

  public class ListComputer extends ComputerendpointRequest<singularity.com.jlpsi.entities.computerendpoint.model.CollectionResponseComputer> {

    private static final String REST_PATH = "computer";

    /**
     * Create a request for the method "listComputer".
     *
     * This request holds the parameters needed by the the computerendpoint server.  After setting any
     * optional parameters, call the {@link ListComputer#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListComputer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListComputer() {
      super(Computerendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.computerendpoint.model.CollectionResponseComputer.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListComputer setAlt(java.lang.String alt) {
      return (ListComputer) super.setAlt(alt);
    }

    @Override
    public ListComputer setFields(java.lang.String fields) {
      return (ListComputer) super.setFields(fields);
    }

    @Override
    public ListComputer setKey(java.lang.String key) {
      return (ListComputer) super.setKey(key);
    }

    @Override
    public ListComputer setOauthToken(java.lang.String oauthToken) {
      return (ListComputer) super.setOauthToken(oauthToken);
    }

    @Override
    public ListComputer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListComputer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListComputer setQuotaUser(java.lang.String quotaUser) {
      return (ListComputer) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListComputer setUserIp(java.lang.String userIp) {
      return (ListComputer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean assigned;

    /**

     */
    public java.lang.Boolean getAssigned() {
      return assigned;
    }

    public ListComputer setAssigned(java.lang.Boolean assigned) {
      this.assigned = assigned;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListComputer setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String schoolId;

    /**

     */
    public java.lang.String getSchoolId() {
      return schoolId;
    }

    public ListComputer setSchoolId(java.lang.String schoolId) {
      this.schoolId = schoolId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListComputer setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListComputer set(String parameterName, Object value) {
      return (ListComputer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeComputer".
   *
   * This request holds the parameters needed by the computerendpoint server.  After setting any
   * optional parameters, call the {@link RemoveComputer#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveComputer removeComputer(java.lang.String id) throws java.io.IOException {
    RemoveComputer result = new RemoveComputer(id);
    initialize(result);
    return result;
  }

  public class RemoveComputer extends ComputerendpointRequest<Void> {

    private static final String REST_PATH = "computer/{id}";

    /**
     * Create a request for the method "removeComputer".
     *
     * This request holds the parameters needed by the the computerendpoint server.  After setting any
     * optional parameters, call the {@link RemoveComputer#execute()} method to invoke the remote
     * operation. <p> {@link RemoveComputer#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveComputer(java.lang.String id) {
      super(Computerendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveComputer setAlt(java.lang.String alt) {
      return (RemoveComputer) super.setAlt(alt);
    }

    @Override
    public RemoveComputer setFields(java.lang.String fields) {
      return (RemoveComputer) super.setFields(fields);
    }

    @Override
    public RemoveComputer setKey(java.lang.String key) {
      return (RemoveComputer) super.setKey(key);
    }

    @Override
    public RemoveComputer setOauthToken(java.lang.String oauthToken) {
      return (RemoveComputer) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveComputer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveComputer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveComputer setQuotaUser(java.lang.String quotaUser) {
      return (RemoveComputer) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveComputer setUserIp(java.lang.String userIp) {
      return (RemoveComputer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveComputer setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveComputer set(String parameterName, Object value) {
      return (RemoveComputer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateComputer".
   *
   * This request holds the parameters needed by the computerendpoint server.  After setting any
   * optional parameters, call the {@link UpdateComputer#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.computerendpoint.model.Computer}
   * @return the request
   */
  public UpdateComputer updateComputer(singularity.com.jlpsi.entities.computerendpoint.model.Computer content) throws java.io.IOException {
    UpdateComputer result = new UpdateComputer(content);
    initialize(result);
    return result;
  }

  public class UpdateComputer extends ComputerendpointRequest<singularity.com.jlpsi.entities.computerendpoint.model.Computer> {

    private static final String REST_PATH = "computer";

    /**
     * Create a request for the method "updateComputer".
     *
     * This request holds the parameters needed by the the computerendpoint server.  After setting any
     * optional parameters, call the {@link UpdateComputer#execute()} method to invoke the remote
     * operation. <p> {@link UpdateComputer#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.computerendpoint.model.Computer}
     * @since 1.13
     */
    protected UpdateComputer(singularity.com.jlpsi.entities.computerendpoint.model.Computer content) {
      super(Computerendpoint.this, "PUT", REST_PATH, content, singularity.com.jlpsi.entities.computerendpoint.model.Computer.class);
    }

    @Override
    public UpdateComputer setAlt(java.lang.String alt) {
      return (UpdateComputer) super.setAlt(alt);
    }

    @Override
    public UpdateComputer setFields(java.lang.String fields) {
      return (UpdateComputer) super.setFields(fields);
    }

    @Override
    public UpdateComputer setKey(java.lang.String key) {
      return (UpdateComputer) super.setKey(key);
    }

    @Override
    public UpdateComputer setOauthToken(java.lang.String oauthToken) {
      return (UpdateComputer) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateComputer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateComputer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateComputer setQuotaUser(java.lang.String quotaUser) {
      return (UpdateComputer) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateComputer setUserIp(java.lang.String userIp) {
      return (UpdateComputer) super.setUserIp(userIp);
    }

    @Override
    public UpdateComputer set(String parameterName, Object value) {
      return (UpdateComputer) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Computerendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Computerendpoint}. */
    @Override
    public Computerendpoint build() {
      return new Computerendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ComputerendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setComputerendpointRequestInitializer(
        ComputerendpointRequestInitializer computerendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(computerendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
