/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-01 at 17:57:57 UTC 
 * Modify at your own risk.
 */

package singularity.com.jlpsi.entities.complaintendpoint;

/**
 * Service definition for Complaintendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ComplaintendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Complaintendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the complaintendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://kiki-ke.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "complaintendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Complaintendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Complaintendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getComplaint".
   *
   * This request holds the parameters needed by the complaintendpoint server.  After setting any
   * optional parameters, call the {@link GetComplaint#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetComplaint getComplaint(java.lang.String id) throws java.io.IOException {
    GetComplaint result = new GetComplaint(id);
    initialize(result);
    return result;
  }

  public class GetComplaint extends ComplaintendpointRequest<singularity.com.jlpsi.entities.complaintendpoint.model.Complaint> {

    private static final String REST_PATH = "complaint/{id}";

    /**
     * Create a request for the method "getComplaint".
     *
     * This request holds the parameters needed by the the complaintendpoint server.  After setting
     * any optional parameters, call the {@link GetComplaint#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetComplaint#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetComplaint(java.lang.String id) {
      super(Complaintendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.complaintendpoint.model.Complaint.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetComplaint setAlt(java.lang.String alt) {
      return (GetComplaint) super.setAlt(alt);
    }

    @Override
    public GetComplaint setFields(java.lang.String fields) {
      return (GetComplaint) super.setFields(fields);
    }

    @Override
    public GetComplaint setKey(java.lang.String key) {
      return (GetComplaint) super.setKey(key);
    }

    @Override
    public GetComplaint setOauthToken(java.lang.String oauthToken) {
      return (GetComplaint) super.setOauthToken(oauthToken);
    }

    @Override
    public GetComplaint setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetComplaint) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetComplaint setQuotaUser(java.lang.String quotaUser) {
      return (GetComplaint) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetComplaint setUserIp(java.lang.String userIp) {
      return (GetComplaint) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetComplaint setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetComplaint set(String parameterName, Object value) {
      return (GetComplaint) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertComplaint".
   *
   * This request holds the parameters needed by the complaintendpoint server.  After setting any
   * optional parameters, call the {@link InsertComplaint#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.complaintendpoint.model.Complaint}
   * @return the request
   */
  public InsertComplaint insertComplaint(singularity.com.jlpsi.entities.complaintendpoint.model.Complaint content) throws java.io.IOException {
    InsertComplaint result = new InsertComplaint(content);
    initialize(result);
    return result;
  }

  public class InsertComplaint extends ComplaintendpointRequest<singularity.com.jlpsi.entities.complaintendpoint.model.Complaint> {

    private static final String REST_PATH = "complaint";

    /**
     * Create a request for the method "insertComplaint".
     *
     * This request holds the parameters needed by the the complaintendpoint server.  After setting
     * any optional parameters, call the {@link InsertComplaint#execute()} method to invoke the remote
     * operation. <p> {@link InsertComplaint#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.complaintendpoint.model.Complaint}
     * @since 1.13
     */
    protected InsertComplaint(singularity.com.jlpsi.entities.complaintendpoint.model.Complaint content) {
      super(Complaintendpoint.this, "POST", REST_PATH, content, singularity.com.jlpsi.entities.complaintendpoint.model.Complaint.class);
    }

    @Override
    public InsertComplaint setAlt(java.lang.String alt) {
      return (InsertComplaint) super.setAlt(alt);
    }

    @Override
    public InsertComplaint setFields(java.lang.String fields) {
      return (InsertComplaint) super.setFields(fields);
    }

    @Override
    public InsertComplaint setKey(java.lang.String key) {
      return (InsertComplaint) super.setKey(key);
    }

    @Override
    public InsertComplaint setOauthToken(java.lang.String oauthToken) {
      return (InsertComplaint) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertComplaint setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertComplaint) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertComplaint setQuotaUser(java.lang.String quotaUser) {
      return (InsertComplaint) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertComplaint setUserIp(java.lang.String userIp) {
      return (InsertComplaint) super.setUserIp(userIp);
    }

    @Override
    public InsertComplaint set(String parameterName, Object value) {
      return (InsertComplaint) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listComplaint".
   *
   * This request holds the parameters needed by the complaintendpoint server.  After setting any
   * optional parameters, call the {@link ListComplaint#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListComplaint listComplaint() throws java.io.IOException {
    ListComplaint result = new ListComplaint();
    initialize(result);
    return result;
  }

  public class ListComplaint extends ComplaintendpointRequest<singularity.com.jlpsi.entities.complaintendpoint.model.CollectionResponseComplaint> {

    private static final String REST_PATH = "complaint";

    /**
     * Create a request for the method "listComplaint".
     *
     * This request holds the parameters needed by the the complaintendpoint server.  After setting
     * any optional parameters, call the {@link ListComplaint#execute()} method to invoke the remote
     * operation. <p> {@link ListComplaint#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListComplaint() {
      super(Complaintendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.complaintendpoint.model.CollectionResponseComplaint.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListComplaint setAlt(java.lang.String alt) {
      return (ListComplaint) super.setAlt(alt);
    }

    @Override
    public ListComplaint setFields(java.lang.String fields) {
      return (ListComplaint) super.setFields(fields);
    }

    @Override
    public ListComplaint setKey(java.lang.String key) {
      return (ListComplaint) super.setKey(key);
    }

    @Override
    public ListComplaint setOauthToken(java.lang.String oauthToken) {
      return (ListComplaint) super.setOauthToken(oauthToken);
    }

    @Override
    public ListComplaint setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListComplaint) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListComplaint setQuotaUser(java.lang.String quotaUser) {
      return (ListComplaint) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListComplaint setUserIp(java.lang.String userIp) {
      return (ListComplaint) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListComplaint setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String schoolId;

    /**

     */
    public java.lang.String getSchoolId() {
      return schoolId;
    }

    public ListComplaint setSchoolId(java.lang.String schoolId) {
      this.schoolId = schoolId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListComplaint setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListComplaint set(String parameterName, Object value) {
      return (ListComplaint) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeComplaint".
   *
   * This request holds the parameters needed by the complaintendpoint server.  After setting any
   * optional parameters, call the {@link RemoveComplaint#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveComplaint removeComplaint(java.lang.String id) throws java.io.IOException {
    RemoveComplaint result = new RemoveComplaint(id);
    initialize(result);
    return result;
  }

  public class RemoveComplaint extends ComplaintendpointRequest<Void> {

    private static final String REST_PATH = "complaint/{id}";

    /**
     * Create a request for the method "removeComplaint".
     *
     * This request holds the parameters needed by the the complaintendpoint server.  After setting
     * any optional parameters, call the {@link RemoveComplaint#execute()} method to invoke the remote
     * operation. <p> {@link RemoveComplaint#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveComplaint(java.lang.String id) {
      super(Complaintendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveComplaint setAlt(java.lang.String alt) {
      return (RemoveComplaint) super.setAlt(alt);
    }

    @Override
    public RemoveComplaint setFields(java.lang.String fields) {
      return (RemoveComplaint) super.setFields(fields);
    }

    @Override
    public RemoveComplaint setKey(java.lang.String key) {
      return (RemoveComplaint) super.setKey(key);
    }

    @Override
    public RemoveComplaint setOauthToken(java.lang.String oauthToken) {
      return (RemoveComplaint) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveComplaint setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveComplaint) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveComplaint setQuotaUser(java.lang.String quotaUser) {
      return (RemoveComplaint) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveComplaint setUserIp(java.lang.String userIp) {
      return (RemoveComplaint) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveComplaint setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveComplaint set(String parameterName, Object value) {
      return (RemoveComplaint) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateComplaint".
   *
   * This request holds the parameters needed by the complaintendpoint server.  After setting any
   * optional parameters, call the {@link UpdateComplaint#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.complaintendpoint.model.Complaint}
   * @return the request
   */
  public UpdateComplaint updateComplaint(singularity.com.jlpsi.entities.complaintendpoint.model.Complaint content) throws java.io.IOException {
    UpdateComplaint result = new UpdateComplaint(content);
    initialize(result);
    return result;
  }

  public class UpdateComplaint extends ComplaintendpointRequest<singularity.com.jlpsi.entities.complaintendpoint.model.Complaint> {

    private static final String REST_PATH = "complaint";

    /**
     * Create a request for the method "updateComplaint".
     *
     * This request holds the parameters needed by the the complaintendpoint server.  After setting
     * any optional parameters, call the {@link UpdateComplaint#execute()} method to invoke the remote
     * operation. <p> {@link UpdateComplaint#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.complaintendpoint.model.Complaint}
     * @since 1.13
     */
    protected UpdateComplaint(singularity.com.jlpsi.entities.complaintendpoint.model.Complaint content) {
      super(Complaintendpoint.this, "PUT", REST_PATH, content, singularity.com.jlpsi.entities.complaintendpoint.model.Complaint.class);
    }

    @Override
    public UpdateComplaint setAlt(java.lang.String alt) {
      return (UpdateComplaint) super.setAlt(alt);
    }

    @Override
    public UpdateComplaint setFields(java.lang.String fields) {
      return (UpdateComplaint) super.setFields(fields);
    }

    @Override
    public UpdateComplaint setKey(java.lang.String key) {
      return (UpdateComplaint) super.setKey(key);
    }

    @Override
    public UpdateComplaint setOauthToken(java.lang.String oauthToken) {
      return (UpdateComplaint) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateComplaint setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateComplaint) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateComplaint setQuotaUser(java.lang.String quotaUser) {
      return (UpdateComplaint) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateComplaint setUserIp(java.lang.String userIp) {
      return (UpdateComplaint) super.setUserIp(userIp);
    }

    @Override
    public UpdateComplaint set(String parameterName, Object value) {
      return (UpdateComplaint) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Complaintendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Complaintendpoint}. */
    @Override
    public Complaintendpoint build() {
      return new Complaintendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ComplaintendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setComplaintendpointRequestInitializer(
        ComplaintendpointRequestInitializer complaintendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(complaintendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
