/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-01 at 17:51:50 UTC 
 * Modify at your own risk.
 */

package singularity.com.jlpsi.entities.packagexendpoint;

/**
 * Service definition for Packagexendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PackagexendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Packagexendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the packagexendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://kiki-ke.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "packagexendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Packagexendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Packagexendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPackageX".
   *
   * This request holds the parameters needed by the packagexendpoint server.  After setting any
   * optional parameters, call the {@link GetPackageX#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetPackageX getPackageX(java.lang.String id) throws java.io.IOException {
    GetPackageX result = new GetPackageX(id);
    initialize(result);
    return result;
  }

  public class GetPackageX extends PackagexendpointRequest<singularity.com.jlpsi.entities.packagexendpoint.model.PackageX> {

    private static final String REST_PATH = "packagex/{id}";

    /**
     * Create a request for the method "getPackageX".
     *
     * This request holds the parameters needed by the the packagexendpoint server.  After setting any
     * optional parameters, call the {@link GetPackageX#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPackageX#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPackageX(java.lang.String id) {
      super(Packagexendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.packagexendpoint.model.PackageX.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPackageX setAlt(java.lang.String alt) {
      return (GetPackageX) super.setAlt(alt);
    }

    @Override
    public GetPackageX setFields(java.lang.String fields) {
      return (GetPackageX) super.setFields(fields);
    }

    @Override
    public GetPackageX setKey(java.lang.String key) {
      return (GetPackageX) super.setKey(key);
    }

    @Override
    public GetPackageX setOauthToken(java.lang.String oauthToken) {
      return (GetPackageX) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPackageX setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPackageX) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPackageX setQuotaUser(java.lang.String quotaUser) {
      return (GetPackageX) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPackageX setUserIp(java.lang.String userIp) {
      return (GetPackageX) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetPackageX setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPackageX set(String parameterName, Object value) {
      return (GetPackageX) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPackageX".
   *
   * This request holds the parameters needed by the packagexendpoint server.  After setting any
   * optional parameters, call the {@link InsertPackageX#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.packagexendpoint.model.PackageX}
   * @return the request
   */
  public InsertPackageX insertPackageX(singularity.com.jlpsi.entities.packagexendpoint.model.PackageX content) throws java.io.IOException {
    InsertPackageX result = new InsertPackageX(content);
    initialize(result);
    return result;
  }

  public class InsertPackageX extends PackagexendpointRequest<singularity.com.jlpsi.entities.packagexendpoint.model.PackageX> {

    private static final String REST_PATH = "packagex";

    /**
     * Create a request for the method "insertPackageX".
     *
     * This request holds the parameters needed by the the packagexendpoint server.  After setting any
     * optional parameters, call the {@link InsertPackageX#execute()} method to invoke the remote
     * operation. <p> {@link InsertPackageX#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.packagexendpoint.model.PackageX}
     * @since 1.13
     */
    protected InsertPackageX(singularity.com.jlpsi.entities.packagexendpoint.model.PackageX content) {
      super(Packagexendpoint.this, "POST", REST_PATH, content, singularity.com.jlpsi.entities.packagexendpoint.model.PackageX.class);
    }

    @Override
    public InsertPackageX setAlt(java.lang.String alt) {
      return (InsertPackageX) super.setAlt(alt);
    }

    @Override
    public InsertPackageX setFields(java.lang.String fields) {
      return (InsertPackageX) super.setFields(fields);
    }

    @Override
    public InsertPackageX setKey(java.lang.String key) {
      return (InsertPackageX) super.setKey(key);
    }

    @Override
    public InsertPackageX setOauthToken(java.lang.String oauthToken) {
      return (InsertPackageX) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPackageX setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPackageX) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPackageX setQuotaUser(java.lang.String quotaUser) {
      return (InsertPackageX) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPackageX setUserIp(java.lang.String userIp) {
      return (InsertPackageX) super.setUserIp(userIp);
    }

    @Override
    public InsertPackageX set(String parameterName, Object value) {
      return (InsertPackageX) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPackageX".
   *
   * This request holds the parameters needed by the packagexendpoint server.  After setting any
   * optional parameters, call the {@link ListPackageX#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPackageX listPackageX() throws java.io.IOException {
    ListPackageX result = new ListPackageX();
    initialize(result);
    return result;
  }

  public class ListPackageX extends PackagexendpointRequest<singularity.com.jlpsi.entities.packagexendpoint.model.CollectionResponsePackageX> {

    private static final String REST_PATH = "packagex";

    /**
     * Create a request for the method "listPackageX".
     *
     * This request holds the parameters needed by the the packagexendpoint server.  After setting any
     * optional parameters, call the {@link ListPackageX#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListPackageX#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPackageX() {
      super(Packagexendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.packagexendpoint.model.CollectionResponsePackageX.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPackageX setAlt(java.lang.String alt) {
      return (ListPackageX) super.setAlt(alt);
    }

    @Override
    public ListPackageX setFields(java.lang.String fields) {
      return (ListPackageX) super.setFields(fields);
    }

    @Override
    public ListPackageX setKey(java.lang.String key) {
      return (ListPackageX) super.setKey(key);
    }

    @Override
    public ListPackageX setOauthToken(java.lang.String oauthToken) {
      return (ListPackageX) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPackageX setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPackageX) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPackageX setQuotaUser(java.lang.String quotaUser) {
      return (ListPackageX) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPackageX setUserIp(java.lang.String userIp) {
      return (ListPackageX) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPackageX setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPackageX setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPackageX set(String parameterName, Object value) {
      return (ListPackageX) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePackageX".
   *
   * This request holds the parameters needed by the packagexendpoint server.  After setting any
   * optional parameters, call the {@link RemovePackageX#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePackageX removePackageX(java.lang.String id) throws java.io.IOException {
    RemovePackageX result = new RemovePackageX(id);
    initialize(result);
    return result;
  }

  public class RemovePackageX extends PackagexendpointRequest<Void> {

    private static final String REST_PATH = "packagex/{id}";

    /**
     * Create a request for the method "removePackageX".
     *
     * This request holds the parameters needed by the the packagexendpoint server.  After setting any
     * optional parameters, call the {@link RemovePackageX#execute()} method to invoke the remote
     * operation. <p> {@link RemovePackageX#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePackageX(java.lang.String id) {
      super(Packagexendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePackageX setAlt(java.lang.String alt) {
      return (RemovePackageX) super.setAlt(alt);
    }

    @Override
    public RemovePackageX setFields(java.lang.String fields) {
      return (RemovePackageX) super.setFields(fields);
    }

    @Override
    public RemovePackageX setKey(java.lang.String key) {
      return (RemovePackageX) super.setKey(key);
    }

    @Override
    public RemovePackageX setOauthToken(java.lang.String oauthToken) {
      return (RemovePackageX) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePackageX setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePackageX) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePackageX setQuotaUser(java.lang.String quotaUser) {
      return (RemovePackageX) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePackageX setUserIp(java.lang.String userIp) {
      return (RemovePackageX) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemovePackageX setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePackageX set(String parameterName, Object value) {
      return (RemovePackageX) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePackageX".
   *
   * This request holds the parameters needed by the packagexendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePackageX#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.packagexendpoint.model.PackageX}
   * @return the request
   */
  public UpdatePackageX updatePackageX(singularity.com.jlpsi.entities.packagexendpoint.model.PackageX content) throws java.io.IOException {
    UpdatePackageX result = new UpdatePackageX(content);
    initialize(result);
    return result;
  }

  public class UpdatePackageX extends PackagexendpointRequest<singularity.com.jlpsi.entities.packagexendpoint.model.PackageX> {

    private static final String REST_PATH = "packagex";

    /**
     * Create a request for the method "updatePackageX".
     *
     * This request holds the parameters needed by the the packagexendpoint server.  After setting any
     * optional parameters, call the {@link UpdatePackageX#execute()} method to invoke the remote
     * operation. <p> {@link UpdatePackageX#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.packagexendpoint.model.PackageX}
     * @since 1.13
     */
    protected UpdatePackageX(singularity.com.jlpsi.entities.packagexendpoint.model.PackageX content) {
      super(Packagexendpoint.this, "PUT", REST_PATH, content, singularity.com.jlpsi.entities.packagexendpoint.model.PackageX.class);
    }

    @Override
    public UpdatePackageX setAlt(java.lang.String alt) {
      return (UpdatePackageX) super.setAlt(alt);
    }

    @Override
    public UpdatePackageX setFields(java.lang.String fields) {
      return (UpdatePackageX) super.setFields(fields);
    }

    @Override
    public UpdatePackageX setKey(java.lang.String key) {
      return (UpdatePackageX) super.setKey(key);
    }

    @Override
    public UpdatePackageX setOauthToken(java.lang.String oauthToken) {
      return (UpdatePackageX) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePackageX setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePackageX) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePackageX setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePackageX) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePackageX setUserIp(java.lang.String userIp) {
      return (UpdatePackageX) super.setUserIp(userIp);
    }

    @Override
    public UpdatePackageX set(String parameterName, Object value) {
      return (UpdatePackageX) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Packagexendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Packagexendpoint}. */
    @Override
    public Packagexendpoint build() {
      return new Packagexendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PackagexendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPackagexendpointRequestInitializer(
        PackagexendpointRequestInitializer packagexendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(packagexendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
