/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-01 at 17:56:38 UTC 
 * Modify at your own risk.
 */

package singularity.com.jlpsi.entities.historyendpoint;

/**
 * Service definition for Historyendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link HistoryendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Historyendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the historyendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://kiki-ke.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "historyendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Historyendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Historyendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getHistory".
   *
   * This request holds the parameters needed by the historyendpoint server.  After setting any
   * optional parameters, call the {@link GetHistory#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetHistory getHistory(java.lang.String id) throws java.io.IOException {
    GetHistory result = new GetHistory(id);
    initialize(result);
    return result;
  }

  public class GetHistory extends HistoryendpointRequest<singularity.com.jlpsi.entities.historyendpoint.model.History> {

    private static final String REST_PATH = "history/{id}";

    /**
     * Create a request for the method "getHistory".
     *
     * This request holds the parameters needed by the the historyendpoint server.  After setting any
     * optional parameters, call the {@link GetHistory#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetHistory#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetHistory(java.lang.String id) {
      super(Historyendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.historyendpoint.model.History.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetHistory setAlt(java.lang.String alt) {
      return (GetHistory) super.setAlt(alt);
    }

    @Override
    public GetHistory setFields(java.lang.String fields) {
      return (GetHistory) super.setFields(fields);
    }

    @Override
    public GetHistory setKey(java.lang.String key) {
      return (GetHistory) super.setKey(key);
    }

    @Override
    public GetHistory setOauthToken(java.lang.String oauthToken) {
      return (GetHistory) super.setOauthToken(oauthToken);
    }

    @Override
    public GetHistory setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetHistory) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetHistory setQuotaUser(java.lang.String quotaUser) {
      return (GetHistory) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetHistory setUserIp(java.lang.String userIp) {
      return (GetHistory) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetHistory setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetHistory set(String parameterName, Object value) {
      return (GetHistory) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertHistory".
   *
   * This request holds the parameters needed by the historyendpoint server.  After setting any
   * optional parameters, call the {@link InsertHistory#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.historyendpoint.model.History}
   * @return the request
   */
  public InsertHistory insertHistory(singularity.com.jlpsi.entities.historyendpoint.model.History content) throws java.io.IOException {
    InsertHistory result = new InsertHistory(content);
    initialize(result);
    return result;
  }

  public class InsertHistory extends HistoryendpointRequest<singularity.com.jlpsi.entities.historyendpoint.model.History> {

    private static final String REST_PATH = "history";

    /**
     * Create a request for the method "insertHistory".
     *
     * This request holds the parameters needed by the the historyendpoint server.  After setting any
     * optional parameters, call the {@link InsertHistory#execute()} method to invoke the remote
     * operation. <p> {@link InsertHistory#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.historyendpoint.model.History}
     * @since 1.13
     */
    protected InsertHistory(singularity.com.jlpsi.entities.historyendpoint.model.History content) {
      super(Historyendpoint.this, "POST", REST_PATH, content, singularity.com.jlpsi.entities.historyendpoint.model.History.class);
    }

    @Override
    public InsertHistory setAlt(java.lang.String alt) {
      return (InsertHistory) super.setAlt(alt);
    }

    @Override
    public InsertHistory setFields(java.lang.String fields) {
      return (InsertHistory) super.setFields(fields);
    }

    @Override
    public InsertHistory setKey(java.lang.String key) {
      return (InsertHistory) super.setKey(key);
    }

    @Override
    public InsertHistory setOauthToken(java.lang.String oauthToken) {
      return (InsertHistory) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertHistory setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertHistory) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertHistory setQuotaUser(java.lang.String quotaUser) {
      return (InsertHistory) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertHistory setUserIp(java.lang.String userIp) {
      return (InsertHistory) super.setUserIp(userIp);
    }

    @Override
    public InsertHistory set(String parameterName, Object value) {
      return (InsertHistory) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listHistory".
   *
   * This request holds the parameters needed by the historyendpoint server.  After setting any
   * optional parameters, call the {@link ListHistory#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListHistory listHistory() throws java.io.IOException {
    ListHistory result = new ListHistory();
    initialize(result);
    return result;
  }

  public class ListHistory extends HistoryendpointRequest<singularity.com.jlpsi.entities.historyendpoint.model.CollectionResponseHistory> {

    private static final String REST_PATH = "history";

    /**
     * Create a request for the method "listHistory".
     *
     * This request holds the parameters needed by the the historyendpoint server.  After setting any
     * optional parameters, call the {@link ListHistory#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListHistory#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListHistory() {
      super(Historyendpoint.this, "GET", REST_PATH, null, singularity.com.jlpsi.entities.historyendpoint.model.CollectionResponseHistory.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListHistory setAlt(java.lang.String alt) {
      return (ListHistory) super.setAlt(alt);
    }

    @Override
    public ListHistory setFields(java.lang.String fields) {
      return (ListHistory) super.setFields(fields);
    }

    @Override
    public ListHistory setKey(java.lang.String key) {
      return (ListHistory) super.setKey(key);
    }

    @Override
    public ListHistory setOauthToken(java.lang.String oauthToken) {
      return (ListHistory) super.setOauthToken(oauthToken);
    }

    @Override
    public ListHistory setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListHistory) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListHistory setQuotaUser(java.lang.String quotaUser) {
      return (ListHistory) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListHistory setUserIp(java.lang.String userIp) {
      return (ListHistory) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListHistory setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListHistory setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListHistory set(String parameterName, Object value) {
      return (ListHistory) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeHistory".
   *
   * This request holds the parameters needed by the historyendpoint server.  After setting any
   * optional parameters, call the {@link RemoveHistory#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveHistory removeHistory(java.lang.String id) throws java.io.IOException {
    RemoveHistory result = new RemoveHistory(id);
    initialize(result);
    return result;
  }

  public class RemoveHistory extends HistoryendpointRequest<Void> {

    private static final String REST_PATH = "history/{id}";

    /**
     * Create a request for the method "removeHistory".
     *
     * This request holds the parameters needed by the the historyendpoint server.  After setting any
     * optional parameters, call the {@link RemoveHistory#execute()} method to invoke the remote
     * operation. <p> {@link RemoveHistory#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveHistory(java.lang.String id) {
      super(Historyendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveHistory setAlt(java.lang.String alt) {
      return (RemoveHistory) super.setAlt(alt);
    }

    @Override
    public RemoveHistory setFields(java.lang.String fields) {
      return (RemoveHistory) super.setFields(fields);
    }

    @Override
    public RemoveHistory setKey(java.lang.String key) {
      return (RemoveHistory) super.setKey(key);
    }

    @Override
    public RemoveHistory setOauthToken(java.lang.String oauthToken) {
      return (RemoveHistory) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveHistory setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveHistory) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveHistory setQuotaUser(java.lang.String quotaUser) {
      return (RemoveHistory) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveHistory setUserIp(java.lang.String userIp) {
      return (RemoveHistory) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveHistory setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveHistory set(String parameterName, Object value) {
      return (RemoveHistory) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateHistory".
   *
   * This request holds the parameters needed by the historyendpoint server.  After setting any
   * optional parameters, call the {@link UpdateHistory#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link singularity.com.jlpsi.entities.historyendpoint.model.History}
   * @return the request
   */
  public UpdateHistory updateHistory(singularity.com.jlpsi.entities.historyendpoint.model.History content) throws java.io.IOException {
    UpdateHistory result = new UpdateHistory(content);
    initialize(result);
    return result;
  }

  public class UpdateHistory extends HistoryendpointRequest<singularity.com.jlpsi.entities.historyendpoint.model.History> {

    private static final String REST_PATH = "history";

    /**
     * Create a request for the method "updateHistory".
     *
     * This request holds the parameters needed by the the historyendpoint server.  After setting any
     * optional parameters, call the {@link UpdateHistory#execute()} method to invoke the remote
     * operation. <p> {@link UpdateHistory#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link singularity.com.jlpsi.entities.historyendpoint.model.History}
     * @since 1.13
     */
    protected UpdateHistory(singularity.com.jlpsi.entities.historyendpoint.model.History content) {
      super(Historyendpoint.this, "PUT", REST_PATH, content, singularity.com.jlpsi.entities.historyendpoint.model.History.class);
    }

    @Override
    public UpdateHistory setAlt(java.lang.String alt) {
      return (UpdateHistory) super.setAlt(alt);
    }

    @Override
    public UpdateHistory setFields(java.lang.String fields) {
      return (UpdateHistory) super.setFields(fields);
    }

    @Override
    public UpdateHistory setKey(java.lang.String key) {
      return (UpdateHistory) super.setKey(key);
    }

    @Override
    public UpdateHistory setOauthToken(java.lang.String oauthToken) {
      return (UpdateHistory) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateHistory setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateHistory) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateHistory setQuotaUser(java.lang.String quotaUser) {
      return (UpdateHistory) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateHistory setUserIp(java.lang.String userIp) {
      return (UpdateHistory) super.setUserIp(userIp);
    }

    @Override
    public UpdateHistory set(String parameterName, Object value) {
      return (UpdateHistory) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Historyendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Historyendpoint}. */
    @Override
    public Historyendpoint build() {
      return new Historyendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link HistoryendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setHistoryendpointRequestInitializer(
        HistoryendpointRequestInitializer historyendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(historyendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
